name: Reusable Cloud SQL Instance Management (Start and Stop)

on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform (start or stop)'
        default: 'stop'
        required: true
        type: string
      instance_names:
        description: 'Comma-separated list of Cloud SQL instance names'
        required: true
        type: string
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_NAME:
        required: true
      GCP_WORKLOAD_IDENTITY_SA_EMAIL:
        required: true
      GCP_PROJECT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  manage-instances:
    name: Manage Cloud SQL Instances
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Manage Cloud SQL Instances
        run: |
          action="${{ inputs.action }}"
          IFS=',' read -r -a instances <<< "${{ inputs.instance_names }}"
          for instance in "${instances[@]}"; do
            echo "Performing action '$action' on instance '$instance'"
            if [ "$action" == "start" ]; then
              gcloud sql instances patch "$instance" --activation-policy=ALWAYS --project=${{ secrets.GCP_PROJECT_ID }}
            elif [ "$action" == "stop" ]; then
              gcloud sql instances patch "$instance" --activation-policy=NEVER --project=${{ secrets.GCP_PROJECT_ID }}
            else
              echo "Invalid action specified."
              exit 1
            fi
          done
