# Workflow: reusable-cloudsql-management.yaml
#
# Description:
#   Reusable workflow to start or stop a Google Cloud SQL instance.
#   It authenticates against Google Cloud using Workload Identity.
#
# Steps:
#   - Authenticate with Google Cloud
#   - Set up Google Cloud SDK
#   - Determine Action (start or stop) based on input
#   - Perform the action on the Cloud SQL instance

name: Reusable Cloud SQL Instance Management (Start and Stop)

on:
  workflow_call:
    inputs:
      action:
        description: 'Action to perform (start or stop)'
        default: 'stop'
        required: true
        type: string
    secrets:
      GCP_CLOUDSQL_INSTANCE:
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER_NAME:
        required: true
      GCP_WORKLOAD_IDENTITY_SA_EMAIL:
        required: true
      GCP_PROJECT_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  run:
    name: Manage Cloud SQL Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Determine Action
        run: |
          action="${{ github.event.inputs.action }}"
          if [ "${{ inputs.action }}" == "start" ]; then
            gcloud sql instances patch ${{secrets.GCP_CLOUDSQL_INSTANCE}} \
              --activation-policy=ALWAYS \
              --project=${{ secrets.GCP_PROJECT_ID }}
          elif [ "${{ inputs.action }}" == "stop" ]; then
            gcloud sql instances patch  ${{secrets.GCP_CLOUDSQL_INSTANCE}} \
              --activation-policy=NEVER \
              --project=${{ secrets.GCP_PROJECT_ID }}
          else
            echo "Invalid action specified."
            exit 1
          fi

